import { ModelGateway } from '../../services/ai/modelGateway';

// --- Interfaces ---

export interface AgentContext {
  sessionId?: string;
  userId?: string;
  previousSteps?: string[]; 
  artifacts?: any[];
  useRAG?: boolean;
  projectId?: string;
  enableReview?: boolean; // Phase 3: Self-Correction Loop
}

export interface AgentGoal {
  description: string;
  constraints?: string[];
}

export interface AgentResult {
  success: boolean;
  output: string; // The final text response or a summary
  artifacts?: any[]; // Generated files, code, etc.
  nextAction?: 'STOP' | 'ASK_USER' | 'DELEGATE';
}

export interface Tool {
  name: string;
  description: string;
  execute: (args: any) => Promise<string>;
  schema?: any; // JSON Schema for the tool arguments
}

// --- Base Agent Class ---

export abstract class BaseAgent {
  protected name: string;
  protected modelId: string;
  protected tools: Tool[];
  
  constructor(name: string, modelId: string = 'gpt-4o', tools: Tool[] = []) {
    this.name = name;
    this.modelId = modelId;
    this.tools = tools;
  }

  abstract getSystemPrompt(): string;

  protected async reviewOutput(output: string, goal: AgentGoal, context: AgentContext): Promise<string> {
      if (!context.enableReview) return output;
      
      console.log(`[Agent: ${this.name}] Self-Correction/Review triggered...`);
      try {
        const reviewPrompt = `
        You are a Quality Assurance AI Auditor.
        Your task is to review the following ANSWER generated by an AI Agent against the original GOAL.

        ORIGINAL GOAL: ${goal.description}
        
        PROPOSED ANSWER:
        ${output}

        INSTRUCTIONS:
        1. Verify accuracy and completeness.
        2. If the answer is satisfactory, output it exactly as is.
        3. If there are errors, hallucinations, or missing parts, REWRITE the answer to correct them.
        4. Do NOT add meta-commentary like "Here is the corrected version". Just give the final text.
        `;

        const result = await ModelGateway.generateText({
            messages: [{ role: 'system', content: "You are a meticulous AI editor." }, { role: 'user', content: reviewPrompt }],
            modelId: 'gpt-4o', 
            temperature: 0
        });

        if (result.reply && result.reply !== output) {
            console.log(`[Agent: ${this.name}] Output was corrected. Length delta: ${result.reply.length - output.length}`);
            return result.reply;
        }
      } catch (e) {
        console.warn(`[Agent: ${this.name}] Review failed, using original output.`);
      }
      return output;
  }

  async run(goal: AgentGoal, context: AgentContext): Promise<AgentResult> {
    console.log(`[Agent: ${this.name}] Starting goal: ${goal.description}`);
    
    // Phase 3: Self-Correction flag
    const shouldReview = context.enableReview ?? false; // Default off to save tokens

    const messages = [
      { role: 'system', content: this.getSystemPrompt() },
      { role: 'user', content: `Goal: ${goal.description}\nContext: ${JSON.stringify(context)}` }
    ];

    // Format tools for OpenAI
    const openAITools = this.tools.map(t => ({
      type: 'function',
      function: {
        name: t.name,
        description: t.description,
        parameters: t.schema
      }
    }));

    try {
      const maxSteps = 5;
      let step = 0;

      while (step < maxSteps) {
        step++;
        
        // 1. Call Model
        const result: any = await ModelGateway.generateText({
          messages,
          modelId: this.modelId,
          temperature: 0.2,
          tools: openAITools.length > 0 ? openAITools : undefined,
          useRAG: context.useRAG,
          projectId: context.projectId
        });

        const { reply, toolCalls } = result;

        // Add assistant message to history
        messages.push({ 
          role: 'assistant', 
          content: reply || '',
          ...(toolCalls ? { tool_calls: toolCalls } : {})
        } as any);

        // 2. Check for Tool Calls
        if (toolCalls && toolCalls.length > 0) {
          console.log(`[Agent: ${this.name}] Processing ${toolCalls.length} tool calls`);
          
          for (const call of toolCalls) {
            const toolName = call.function.name;
            const args = JSON.parse(call.function.arguments);
            
            const tool = this.tools.find(t => t.name === toolName);
            let toolResult = "Error: Tool not found";

            if (tool) {
              try {
                console.log(`[Agent: ${this.name}] Executing tool: ${toolName}`);
                toolResult = await tool.execute(args);
              } catch (e: any) {
                toolResult = `Error executing tool: ${e.message}`;
              }
            }

            // Report result back to model
            messages.push({
              role: 'tool',
              tool_call_id: call.id,
              content: toolResult
            } as any);
          }
          // Loop continues to get the model's interpretation of tool results
        } else {
          // No tools called, we have a final answer
          console.log(`[Agent: ${this.name}] Final Answer proposed:`, reply ? reply.substring(0, 50) + '...' : 'Empty');
          
          const finalOutput = await this.reviewOutput(reply || "No response generated.", goal, context);
          
          return {
            success: true,
            output: finalOutput
          };
        }
      }

      return {
        success: false,
        output: "Agent execution max steps reached."
      };

    } catch (error: any) {
      console.error(`[Agent: ${this.name}] Error:`, error);
      return {
        success: false,
        output: `Agent failed: ${error.message}`
      };
    }
  }
}
